# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tik.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QGridLayout, QLabel, QPushButton
from PyQt5.QtGui import QPixmap, QCursor
from PyQt5 import QtCore
from urllib.request import urlopen
import json
import random


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(324, 402)
        self.L1 = QtWidgets.QPushButton(Dialog)
        self.L1.setGeometry(QtCore.QRect(20, 30, 75, 71))
        self.L1.setIconSize(QtCore.QSize(20, 20))
        self.L1.setCheckable(False)
        self.L1.setObjectName("L1")
        self.L2 = QtWidgets.QPushButton(Dialog)
        self.L2.setGeometry(QtCore.QRect(120, 30, 75, 71))
        self.L2.setObjectName("L2")
        self.L3 = QtWidgets.QPushButton(Dialog)
        self.L3.setGeometry(QtCore.QRect(220, 30, 71, 71))
        self.L3.setObjectName("L3")
        self.L22 = QtWidgets.QPushButton(Dialog)
        self.L22.setGeometry(QtCore.QRect(120, 130, 75, 71))
        self.L22.setObjectName("L22")
        self.L32 = QtWidgets.QPushButton(Dialog)
        self.L32.setGeometry(QtCore.QRect(220, 130, 75, 71))
        self.L32.setObjectName("L32")
        self.L12 = QtWidgets.QPushButton(Dialog)
        self.L12.setGeometry(QtCore.QRect(20, 130, 75, 71))
        self.L12.setObjectName("L12")
        self.L23 = QtWidgets.QPushButton(Dialog)
        self.L23.setGeometry(QtCore.QRect(120, 230, 75, 71))
        self.L23.setObjectName("L23")
        self.L33 = QtWidgets.QPushButton(Dialog)
        self.L33.setGeometry(QtCore.QRect(220, 230, 75, 71))
        self.L33.setObjectName("L33")
        self.L13 = QtWidgets.QPushButton(Dialog)
        self.L13.setGeometry(QtCore.QRect(20, 230, 75, 71))
        self.L13.setObjectName("L13")
        self.A = QtWidgets.QPushButton
        self.L1.clicked.connect(self.contador)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("TA TE TI", "TA TE TI"))
        self.L1.setText(_translate("Dialog", "x"))
        self.L1.setStyleSheet("border: 4px solid ")
        self.L2.setText(_translate("Dialog", "PushButton"))
        self.L3.setText(_translate("Dialog", "PushButton"))
        self.L22.setText(_translate("Dialog", "PushButton"))
        self.L32.setText(_translate("Dialog", "PushButton"))
        self.L12.setText(_translate("Dialog", "PushButton"))
        self.L23.setText(_translate("Dialog", "PushButton"))
        self.L33.setText(_translate("Dialog", "PushButton"))
        self.L13.setText(_translate("Dialog", "PushButton"))

        def activar1(self):
            self.L1.setEnabled(False)
            self.L1.setText("X")
            self.L1.setStyleSheet("border: 4px solid ;")
            self.L1.setStyleSheet("color: green ;")
            self.L1.setStyleSheet("background: '#BC006C'")

    def activar1L1(self):
        self.L1.setEnabled(False)
        self.L1.setText("O")
        self.L1.setStyleSheet("border: 4px solid ;")
        self.L1.setStyleSheet("color: green ;")
        self.L1.setStyleSheet("background: '#BC0006C'")

    def activar1L2(self):
        self.L2.setEnabled(False)
        self.L2.setText("O")
        self.L2.setStyleSheet("border: 4px solid ;")
        self.L2.setStyleSheet("color: green ;")
        self.L2.setStyleSheet("background: '#BC0006C'")

    def activar1L3(self):
        self.L3.setEnabled(False)
        self.L3.setText("O")
        self.L3.setStyleSheet("border: 4px solid ;")
        self.L3.setStyleSheet("color: green ;")
        self.L3.setStyleSheet("background: '#BC0006C'")

    def activar2L1(self):
        self.L1.setEnabled(False)
        self.L1.setText("O")
        self.L1.setStyleSheet("border: 4px solid ;")
        self.L1.setStyleSheet("color: green ;")
        self.L1.setStyleSheet("background: '#BC0100B'")

    def activar2L2(self):
        self.L1.setEnabled(False)
        self.L1.setText("O")
        self.L1.setStyleSheet("border: 4px solid ;")
        self.L1.setStyleSheet("color: green ;")
        self.L1.setStyleSheet("background: '#BC0100B'")

    def activar2L3(self):
        self.L1.setEnabled(False)
        self.L1.setText("O")
        self.L1.setStyleSheet("border: 4px solid ;")
        self.L1.setStyleSheet("color: green ;")
        self.L1.setStyleSheet("background: '#BC0100B'")

    def activador(self):
        if self.L1.clicked or self.L2.clicked or self.L3.clicked:
            self.contador

    def contador(self):
        contador = 0
        if contador == 0:
            self.player1
        elif contador == 1:
            self.player2

    def player1(self):
        self.L1.clicked.connect(self.activar1L1)
        self.L2.clicked.connect(self.activar1L2)
        self.L3.clicked.connect(self.activar1L3)

    def player2(self):
        self.L1.clicked.connect(self.activar2L1)
        self.L2.clicked.connect(self.activar2L2)
        self.L3.clicked.connect(self.activar2L3)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
